### PR TITLE
Update release.yml

### PR DESCRIPTION
**Pull request by amitbind13**

### CODE REVIEW

**Comment by zeke** [comment]
Hi. Can you explain what this change is about?

**Comment by mdrijwan** [comment]
> Hi. Can you explain what this change is about?

hi @zeke, i think this is because github now doesn't allow a token to be named which starts with `GITHUB`. however, it's suggested by github for the token to be named as `GH_AUTH_TOKEN`. i will push a commit for that.

**Comment by zeke** [comment]
Aha. Thanks for the explanation, @mdrijwan

**Comment by mdrijwan** [comment]
> Aha. Thanks for the explanation, @mdrijwan

my pleasure man! cheers!!

**Pull request closed without merging**
